[package]
name = "klu-sys"
version = "0.1.0"
edition = "2021"
target = "x86_64-pc-windows-gnu"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
bindgen = "^0.71.1"
